Add ruff
mhthies/smarthomeconnect pull request #100
Opened 2024-12-01 21:26 UTC by jo47011

Replace all the original project setubt, linting, etc. with ruff.

Still WIP.

2024-12-01 21:28 UTC, jo47011 commented
Sorry this one was to early.  Wanted a PR in my fork only so you do not get all the notifications.  Will close this one and open a new one once I'm ready.

2024-12-04 15:50 UTC, jo47011 commented on .github/workflows/build.yml
> +        mkdir _static
Do we want this here to avoid the warning?

`WARNING: html_static_path entry '_static' does not exist`

2024-12-04 15:53 UTC, jo47011 commented on pyproject.toml
> +ignore = [
All the errors below occur.  As proposed we can enable and fix them one by one in step 3.

2024-12-04 15:56 UTC, jo47011 commented on scripts/extract_dependencies.py
> +"""Extract the names int the [project.optional-dependencies] section of a pyproject.toml file.
Not sure where to put the script.  Let me know whether you prefer it somewhere else.  

I don't like the need for such a script in the 1st place but there seems to be no generic way like `pip install .[all]` when using `pyproject.toml`.  Using this scripts avoids repeating dependencies which would be hard to maintain in the long run, e.g.
```python
   pip install .[mysql,knx,dmx,midi,mqtt,pulse,telegram,file_persistence]
```
So for me the script is the better choice.

2024-12-04 16:20 UTC, jo47011 commented on test/interfaces/test_midi.py
> +
Needed to move the import here.

Avoids the `pip uninstall python-rtmidi` to skip those tests.  Not sure whether this is really the best logic as this happens quietly and might not be noticed if skipped accidently.

2024-12-04 16:21 UTC, jo47011 commented on test/interfaces/test_midi.py
> +@unittest.skipUnless(mido_backend_available, "mido MIDI backend is not available: {}".format(mido_backend_error))
This line is new to skip this test as well.  Other `@unittest.skipUnless` changes is a typo fix only ("available").

2024-12-04 16:30 UTC, jo47011 commented on test/test_interfaces_stub.py
> -        import shc.interfaces.midi  # noqa: F401
Had to remove this one.  Well it is tested in test_midi.py which is skipped in the pipeline.  

Is my current proposal sufficient or do you feel like we need this test here?  Then we rollback to your approach and install `midi` but uninstall `python-rtmidi` which is kind of confusing to me.  Maybe we should split the dependency then.

2024-12-04 16:48 UTC, jo47011 commented
As for the failed code coverage report, I suggest we fix it once we have the test strategy for the `midi` stuff clarified.
Can't we just mock the failing midi tests:
```sh
_rtmidi.SystemError: MidiInAlsa::initialize: error creating ALSA sequencer client object.
```

2024-12-11 22:14 UTC, jo47011 commented
Hi @mhthies, don't want to push you (seriously not).  Just want to make sure we're on the same page.  I would like you to make a 1st review and provide some feedback.  I know not all checks are passing right now but the fix would depend on the result of our discussion.  Feel assigned as reviewer to this PR 😉 No rush, I'm also quite busy right now.

2024-12-31 15:48 UTC, mhthies commented on setup.py
I think the `setup.py` is still required, even with all the other changes. Otherwise, the web assets are not installed and compiled to be packaged in the wheel distribution. Or did I overlook something?

2024-12-31 15:49 UTC, mhthies commented
On the midi tests:

In general, the MIDO tests only work when one of the MIDO backends is installed. Thus, I decided to make skipping the tests dependent on the availability of a MIDO backend.

In addition, we have the problem that the MIDI tests fail on GitHub Actions due to a missing kernel module/option which is required for creating MIDI ports, including loopback ports (i.e. MIDO output ports with `virtual=True`). Uninstalling the `rt-midi` package on GitHub Actions is a workaround to get the correct behavior: Although, *technically* a MIDO backend is available on Linux, using rt-midi, it is not functional in GitHub Actions. So, the tests should treat this platform as if there were no MIDO backend.

To get at least some basic coverage of the Python code, we have the "stub tests" which simply imports the python module without executing any function. This would still detect syntax or import errors.

Do you see a reason to change this behavior?

2025-01-04 20:58 UTC, jo47011 commented
> In general, the MIDO tests only work when one of the MIDO backends is installed. Thus, I decided to make skipping the tests dependent on the availability of a MIDO backend.
> 
> In addition, we have the problem that the MIDI tests fail on GitHub Actions due to a missing kernel module/option which is required for creating MIDI ports, including loopback ports (i.e. MIDO output ports with `virtual=True`). Uninstalling the `rt-midi` package on GitHub Actions is a workaround to get the correct behavior: Although, _technically_ a MIDO backend is available on Linux, using rt-midi, it is not functional in GitHub Actions. So, the tests should treat this platform as if there were no MIDO backend.

I understand your approach and the missing option of having those tests run on GitHub Actions.  I just didn't like "pip uninstall python-rtmidi" in the build.yml to achieve it.  But I have no strong opinion on that so I will roll back the changes to keep the diffs of this PR as small as possible.

> 
> To get at least some basic coverage of the Python code, we have the "stub tests" which simply imports the python module without executing any function. This would still detect syntax or import errors.
> 
> Do you see a reason to change this behavior?

To be honest I did not see the `detect syntax or import errors` benefit.  As for this reason I now understand your approach.

2025-01-04 21:21 UTC, jo47011 commented on setup.py
You are totally right.  I missed out on the npm install.  I'll put it back in.

2025-01-12 18:16 UTC, mhthies requested changes

2025-01-12 18:16 UTC, mhthies commented on scripts/extract_dependencies.py
> +        return []
Please, don't parse TOML with a RegEx.

I see that we cannot reliably use `tomli` as a dependency for Python  < 3.10 here, cause this script is used to to figure out the dependencies, in the first place. Maybe we should try to avoid this script alltogether and instead write the full list of extras/features into every pip invocation? I'd actually find that okay.

Yes, I know, I was okay with the separate list of dependencies in the requirements.txt, as well, which had obvious disadvantages. However, with a duplicated list of extras which does not match completely, we would more likely see a failure in the CI pipeline.

So, in conclusion, I'd prefer not using this script but hardcoding the list of extras/features.

2025-01-16 07:44 UTC, jo47011 commented on pyproject.toml
> +# quote-style = "double"
This would cause a lot of changes and the key changes of this PR could easily be overseen.  Once we have the strategy clear we do it step by step, e.g. one PR only for replacing ' => ".

2025-01-16 07:48 UTC, jo47011 commented on README.md
> +To run the static type checks and codestyle checks locally, simply install MyPy and flake8 and execute the `mypy` command in the shc project repository.
Remove sphinx config option.  Of course this is the better approach:
# html_static_path = ['_static']

Removed flak8 from README.

2025-01-16 08:02 UTC, jo47011 commented on setup.cfg
> -shc.web = static/pack/*
```bash
python -m build --sdist

tar tvzf ./dist/smarthomeconnect-0.9.0.tar.gz

smarthomeconnect-0.9.0/
smarthomeconnect-0.9.0/LICENSE
smarthomeconnect-0.9.0/MANIFEST.in
smarthomeconnect-0.9.0/NOTICE
smarthomeconnect-0.9.0/PKG-INFO
smarthomeconnect-0.9.0/README.md
smarthomeconnect-0.9.0/package.json
smarthomeconnect-0.9.0/pyproject.toml
smarthomeconnect-0.9.0/setup.cfg
smarthomeconnect-0.9.0/setup.py
smarthomeconnect-0.9.0/shc/
smarthomeconnect-0.9.0/shc/__init__.py
smarthomeconnect-0.9.0/shc/base.py
smarthomeconnect-0.9.0/shc/conversion.py
smarthomeconnect-0.9.0/shc/data_logging.py
smarthomeconnect-0.9.0/shc/datatypes.py
smarthomeconnect-0.9.0/shc/expressions.py
smarthomeconnect-0.9.0/shc/interfaces/
smarthomeconnect-0.9.0/shc/interfaces/__init__.py
smarthomeconnect-0.9.0/shc/interfaces/_helper.py
smarthomeconnect-0.9.0/shc/interfaces/_pulse_ffi.py
smarthomeconnect-0.9.0/shc/interfaces/command.py
smarthomeconnect-0.9.0/shc/interfaces/dmx.py
smarthomeconnect-0.9.0/shc/interfaces/file_persistence.py
smarthomeconnect-0.9.0/shc/interfaces/in_memory_data_logging.py
smarthomeconnect-0.9.0/shc/interfaces/knx.py
smarthomeconnect-0.9.0/shc/interfaces/midi.py
smarthomeconnect-0.9.0/shc/interfaces/mqtt.py
smarthomeconnect-0.9.0/shc/interfaces/mysql.py
smarthomeconnect-0.9.0/shc/interfaces/ping.py
smarthomeconnect-0.9.0/shc/interfaces/pulse.py
smarthomeconnect-0.9.0/shc/interfaces/shc_client.py
smarthomeconnect-0.9.0/shc/interfaces/system_monitoring.py
smarthomeconnect-0.9.0/shc/interfaces/tasmota.py
smarthomeconnect-0.9.0/shc/interfaces/telegram.py
smarthomeconnect-0.9.0/shc/misc.py
smarthomeconnect-0.9.0/shc/py.typed
smarthomeconnect-0.9.0/shc/supervisor.py
smarthomeconnect-0.9.0/shc/timer.py
smarthomeconnect-0.9.0/shc/util/
smarthomeconnect-0.9.0/shc/util/__init__.py
smarthomeconnect-0.9.0/shc/util/check_shc.py
smarthomeconnect-0.9.0/shc/util/mypy_variable_plugin.py
smarthomeconnect-0.9.0/shc/variables.py
smarthomeconnect-0.9.0/shc/web/
smarthomeconnect-0.9.0/shc/web/__init__.py
smarthomeconnect-0.9.0/shc/web/interface.py
smarthomeconnect-0.9.0/shc/web/log_widgets.py
smarthomeconnect-0.9.0/shc/web/static/
smarthomeconnect-0.9.0/shc/web/static/apple-touch-icon.png
smarthomeconnect-0.9.0/shc/web/static/favicon.ico
smarthomeconnect-0.9.0/shc/web/templates/
smarthomeconnect-0.9.0/shc/web/templates/base.htm
smarthomeconnect-0.9.0/shc/web/templates/buttons.inc.htm
smarthomeconnect-0.9.0/shc/web/templates/log/
smarthomeconnect-0.9.0/shc/web/templates/log/chart.htm
smarthomeconnect-0.9.0/shc/web/templates/log/loglist.htm
smarthomeconnect-0.9.0/shc/web/templates/page.htm
smarthomeconnect-0.9.0/shc/web/templates/status.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/
smarthomeconnect-0.9.0/shc/web/templates/widgets/buttongroup.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/colorchoser.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/hiderowbox.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/imagemap.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/select.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/slider.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/switch.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/textdisplay.htm
smarthomeconnect-0.9.0/shc/web/templates/widgets/textinput.htm
smarthomeconnect-0.9.0/shc/web/widgets.py
smarthomeconnect-0.9.0/smarthomeconnect.egg-info/
smarthomeconnect-0.9.0/smarthomeconnect.egg-info/PKG-INFO
smarthomeconnect-0.9.0/smarthomeconnect.egg-info/SOURCES.txt
smarthomeconnect-0.9.0/smarthomeconnect.egg-info/dependency_links.txt
smarthomeconnect-0.9.0/smarthomeconnect.egg-info/requires.txt
smarthomeconnect-0.9.0/smarthomeconnect.egg-info/top_level.txt
smarthomeconnect-0.9.0/test/
smarthomeconnect-0.9.0/test/test_base.py
smarthomeconnect-0.9.0/test/test_conversion.py
smarthomeconnect-0.9.0/test/test_data_logging.py
smarthomeconnect-0.9.0/test/test_datatypes.py
smarthomeconnect-0.9.0/test/test_examples.py
smarthomeconnect-0.9.0/test/test_expressions.py
smarthomeconnect-0.9.0/test/test_interfaces_stub.py
smarthomeconnect-0.9.0/test/test_misc.py
smarthomeconnect-0.9.0/test/test_timer.py
smarthomeconnect-0.9.0/test/test_variables.py
smarthomeconnect-0.9.0/test/test_web.py
smarthomeconnect-0.9.0/web_ui_src/
smarthomeconnect-0.9.0/web_ui_src/main.css
smarthomeconnect-0.9.0/web_ui_src/main.js
smarthomeconnect-0.9.0/web_ui_src/prism.png
smarthomeconnect-0.9.0/web_ui_src/shc_base.js
smarthomeconnect-0.9.0/web_ui_src/widgets/
smarthomeconnect-0.9.0/web_ui_src/widgets/basic_widgets.js
smarthomeconnect-0.9.0/web_ui_src/widgets/colorchoser_widget.css
smarthomeconnect-0.9.0/web_ui_src/widgets/colorchoser_widget.js
smarthomeconnect-0.9.0/web_ui_src/widgets/hiderow_widget.css
smarthomeconnect-0.9.0/web_ui_src/widgets/log_list_widget.css
smarthomeconnect-0.9.0/web_ui_src/widgets/log_widgets.js
smarthomeconnect-0.9.0/web_ui_src/widgets/slider_widget.css
smarthomeconnect-0.9.0/web_ui_src/widgets/switch_widget.css
```

2025-01-16 08:06 UTC, jo47011 commented on setup.cfg
> -    test.*
```bash
python -m build --wheel

unzip -l dist/smarthomeconnect-0.9.0-py3-none-any.whl

Archive:  dist/smarthomeconnect-0.9.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      835  2024-10-19 13:20   shc/__init__.py
    30795  2024-12-04 10:51   shc/base.py
     3642  2024-12-04 10:51   shc/conversion.py
    36924  2024-12-04 10:51   shc/data_logging.py
    12113  2024-12-04 10:51   shc/datatypes.py
    29107  2024-12-04 10:51   shc/expressions.py
    20590  2024-12-04 10:51   shc/misc.py
        0  2024-10-19 13:20   shc/py.typed
     9588  2024-12-04 10:51   shc/supervisor.py
    54705  2024-12-04 10:51   shc/timer.py
    10452  2024-12-04 10:51   shc/variables.py
        0  2024-10-19 13:20   shc/interfaces/__init__.py
    20544  2024-12-04 10:51   shc/interfaces/_helper.py
     2345  2024-12-04 10:51   shc/interfaces/_pulse_ffi.py
     4829  2024-12-04 10:51   shc/interfaces/command.py
     8417  2024-12-04 10:51   shc/interfaces/dmx.py
    10022  2024-12-04 10:51   shc/interfaces/file_persistence.py
     3755  2024-12-04 10:51   shc/interfaces/in_memory_data_logging.py
    17325  2024-12-04 10:51   shc/interfaces/knx.py
    19371  2024-12-04 10:51   shc/interfaces/midi.py
    18925  2024-12-04 10:51   shc/interfaces/mqtt.py
    16625  2024-12-04 10:51   shc/interfaces/mysql.py
     2963  2024-12-04 10:51   shc/interfaces/ping.py
    37059  2024-12-04 10:51   shc/interfaces/pulse.py
    19493  2024-12-04 10:51   shc/interfaces/shc_client.py
     5569  2024-12-04 10:51   shc/interfaces/system_monitoring.py
    37117  2024-12-04 10:51   shc/interfaces/tasmota.py
    30646  2024-12-04 10:51   shc/interfaces/telegram.py
        0  2024-10-19 13:20   shc/util/__init__.py
     4463  2024-12-04 10:51   shc/util/check_shc.py
     3511  2024-12-04 10:51   shc/util/mypy_variable_plugin.py
       34  2024-12-04 10:51   shc/web/__init__.py
    56395  2024-12-04 10:51   shc/web/interface.py
    13620  2024-12-04 10:51   shc/web/log_widgets.py
    41909  2024-12-04 10:51   shc/web/widgets.py
     4727  2024-10-19 13:20   shc/web/static/apple-touch-icon.png
     1150  2024-10-19 13:20   shc/web/static/favicon.ico
   291164  2024-11-02 19:33   shc/web/static/pack/Lato-Bold.367f6330.woff
   178868  2024-11-04 21:47   shc/web/static/pack/Lato-Bold.59265338.woff2
   178868  2024-11-02 19:33   shc/web/static/pack/Lato-Bold.b0c7a5bb.woff2
   291164  2024-11-04 21:47   shc/web/static/pack/Lato-Bold.be904d71.woff
   188332  2024-11-02 19:33   shc/web/static/pack/Lato-BoldItalic.86b3f184.woff2
   303376  2024-11-02 19:33   shc/web/static/pack/Lato-BoldItalic.a844a9b2.woff
   303376  2024-11-04 21:47   shc/web/static/pack/Lato-BoldItalic.b5212685.woff
   188332  2024-11-04 21:47   shc/web/static/pack/Lato-BoldItalic.e844b943.woff2
   308540  2024-11-04 21:47   shc/web/static/pack/Lato-Italic.1c3dc9f6.woff
   190608  2024-11-02 19:33   shc/web/static/pack/Lato-Italic.c1782172.woff2
   308540  2024-11-02 19:33   shc/web/static/pack/Lato-Italic.eab68376.woff
   190608  2024-11-04 21:47   shc/web/static/pack/Lato-Italic.ef1b93fb.woff2
   178044  2024-11-04 21:47   shc/web/static/pack/Lato-Regular.1380e58c.woff2
   290956  2024-11-04 21:47   shc/web/static/pack/Lato-Regular.175e0a67.woff
   290956  2024-11-02 19:33   shc/web/static/pack/Lato-Regular.96b82b78.woff
   178044  2024-11-02 19:33   shc/web/static/pack/Lato-Regular.ebc7de56.woff2
    33616  2024-11-02 19:33   shc/web/static/pack/LatoLatin-Bold.8431ae36.woff2
    33616  2024-11-04 21:47   shc/web/static/pack/LatoLatin-Bold.b879207a.woff2
    45416  2024-11-02 19:33   shc/web/static/pack/LatoLatin-Bold.c7218d37.woff
    45416  2024-11-04 21:47   shc/web/static/pack/LatoLatin-Bold.f85d624b.woff
    46468  2024-11-02 19:33   shc/web/static/pack/LatoLatin-BoldItalic.26f6ffbc.woff
    46468  2024-11-04 21:47   shc/web/static/pack/LatoLatin-BoldItalic.70f3e341.woff
    34752  2024-11-04 21:47   shc/web/static/pack/LatoLatin-BoldItalic.a17079a7.woff2
    34752  2024-11-02 19:33   shc/web/static/pack/LatoLatin-BoldItalic.a8e39bbd.woff2
    34848  2024-11-04 21:47   shc/web/static/pack/LatoLatin-Italic.414fbd89.woff2
    34848  2024-11-02 19:33   shc/web/static/pack/LatoLatin-Italic.d2089e8b.woff2
    46980  2024-11-02 19:33   shc/web/static/pack/LatoLatin-Italic.de0574c8.woff
    46980  2024-11-04 21:47   shc/web/static/pack/LatoLatin-Italic.e333a4a5.woff
    33828  2024-11-04 21:47   shc/web/static/pack/LatoLatin-Regular.45b5be36.woff2
    45632  2024-11-04 21:47   shc/web/static/pack/LatoLatin-Regular.6f71ea1b.woff
    45632  2024-11-02 19:33   shc/web/static/pack/LatoLatin-Regular.a124b19d.woff
    33828  2024-11-02 19:33   shc/web/static/pack/LatoLatin-Regular.b321314c.woff2
    76736  2024-11-02 19:33   shc/web/static/pack/brand-icons.0b52c614.woff2
    76736  2024-11-04 21:47   shc/web/static/pack/brand-icons.8b67633d.woff2
    89988  2024-11-02 19:33   shc/web/static/pack/brand-icons.a0b02584.woff
    89988  2024-11-04 21:47   shc/web/static/pack/brand-icons.b7e862ad.woff
    78268  2024-11-02 19:33   shc/web/static/pack/icons.6002b354.woff2
   101648  2024-11-02 19:33   shc/web/static/pack/icons.80005ece.woff
   101648  2024-11-04 21:47   shc/web/static/pack/icons.c430880e.woff
    78268  2024-11-04 21:47   shc/web/static/pack/icons.c8ed78b5.woff2
  1602056  2025-01-05 20:36   shc/web/static/pack/main.css
  4046141  2025-01-05 20:36   shc/web/static/pack/main.css.map
  2119903  2024-11-04 21:47   shc/web/static/pack/main.js
  3762643  2024-11-04 21:47   shc/web/static/pack/main.js.map
    16276  2024-11-02 19:33   shc/web/static/pack/outline-icons.09c79cc5.woff
    16276  2024-11-04 21:47   shc/web/static/pack/outline-icons.2c14f812.woff
    13224  2024-11-02 19:33   shc/web/static/pack/outline-icons.5bedcec6.woff2
    13224  2024-11-04 21:47   shc/web/static/pack/outline-icons.e37142a3.woff2
     9697  2024-11-04 21:47   shc/web/static/pack/prism.403685ff.png
     8886  2024-11-02 19:33   shc/web/static/pack/prism.810162de.png
     4800  2024-12-01 15:28   shc/web/templates/base.htm
     1209  2024-10-19 13:20   shc/web/templates/buttons.inc.htm
     1558  2024-10-19 13:20   shc/web/templates/page.htm
     2685  2024-10-19 13:20   shc/web/templates/status.htm
      159  2024-10-19 13:20   shc/web/templates/log/chart.htm
      237  2024-10-19 13:20   shc/web/templates/log/loglist.htm
      423  2024-10-31 09:16   shc/web/templates/widgets/buttongroup.htm
       56  2024-10-19 13:20   shc/web/templates/widgets/colorchoser.htm
      509  2024-10-19 13:20   shc/web/templates/widgets/hiderowbox.htm
     1485  2024-10-19 13:20   shc/web/templates/widgets/imagemap.htm
      415  2024-10-19 13:20   shc/web/templates/widgets/select.htm
      587  2024-10-19 13:20   shc/web/templates/widgets/slider.htm
      430  2024-10-19 13:20   shc/web/templates/widgets/switch.htm
      169  2024-10-19 13:20   shc/web/templates/widgets/textdisplay.htm
      629  2024-10-19 13:20   shc/web/templates/widgets/textinput.htm
    11358  2025-01-16 08:03   smarthomeconnect-0.9.0.dist-info/LICENSE
    26964  2025-01-16 08:03   smarthomeconnect-0.9.0.dist-info/METADATA
      375  2025-01-16 08:03   smarthomeconnect-0.9.0.dist-info/NOTICE
       91  2025-01-16 08:03   smarthomeconnect-0.9.0.dist-info/WHEEL
        4  2025-01-16 08:03   smarthomeconnect-0.9.0.dist-info/top_level.txt
    10044  2025-01-16 08:03   smarthomeconnect-0.9.0.dist-info/RECORD
---------                     -------
 17458214                     108 files

```

2025-01-16 08:16 UTC, jo47011 commented on pyproject.toml
> +]
You are so right, changed it to:

```bash
include = ["shc/**/*.py", "test/**/*.py"]
exclude = ["test/assets"]
```
```bash
ruff check . --show-files
smarthomeconnect/shc/__init__.py
smarthomeconnect/shc/base.py
smarthomeconnect/shc/conversion.py
smarthomeconnect/shc/data_logging.py
smarthomeconnect/shc/datatypes.py
smarthomeconnect/shc/expressions.py
smarthomeconnect/shc/interfaces/__init__.py
smarthomeconnect/shc/interfaces/_helper.py
smarthomeconnect/shc/interfaces/_pulse_ffi.py
smarthomeconnect/shc/interfaces/command.py
smarthomeconnect/shc/interfaces/dmx.py
smarthomeconnect/shc/interfaces/file_persistence.py
smarthomeconnect/shc/interfaces/in_memory_data_logging.py
smarthomeconnect/shc/interfaces/knx.py
smarthomeconnect/shc/interfaces/midi.py
smarthomeconnect/shc/interfaces/mqtt.py
smarthomeconnect/shc/interfaces/mysql.py
smarthomeconnect/shc/interfaces/ping.py
smarthomeconnect/shc/interfaces/pulse.py
smarthomeconnect/shc/interfaces/shc_client.py
smarthomeconnect/shc/interfaces/system_monitoring.py
smarthomeconnect/shc/interfaces/tasmota.py
smarthomeconnect/shc/interfaces/telegram.py
smarthomeconnect/shc/misc.py
smarthomeconnect/shc/supervisor.py
smarthomeconnect/shc/timer.py
smarthomeconnect/shc/util/__init__.py
smarthomeconnect/shc/util/check_shc.py
smarthomeconnect/shc/util/mypy_variable_plugin.py
smarthomeconnect/shc/variables.py
smarthomeconnect/shc/web/__init__.py
smarthomeconnect/shc/web/interface.py
smarthomeconnect/shc/web/log_widgets.py
smarthomeconnect/shc/web/widgets.py
smarthomeconnect/test/__init__.py
smarthomeconnect/test/_helper.py
smarthomeconnect/test/interfaces/__init__.py
smarthomeconnect/test/interfaces/test_command.py
smarthomeconnect/test/interfaces/test_file_persistence.py
smarthomeconnect/test/interfaces/test_in_memory_data_logging.py
smarthomeconnect/test/interfaces/test_knx.py
smarthomeconnect/test/interfaces/test_midi.py
smarthomeconnect/test/interfaces/test_mqtt.py
smarthomeconnect/test/interfaces/test_mysql.py
smarthomeconnect/test/interfaces/test_ping.py
smarthomeconnect/test/interfaces/test_pulse.py
smarthomeconnect/test/interfaces/test_shc_client.py
smarthomeconnect/test/interfaces/test_system_monitoring.py
smarthomeconnect/test/interfaces/test_tasmota.py
smarthomeconnect/test/interfaces/test_telegram.py
smarthomeconnect/test/test_base.py
smarthomeconnect/test/test_conversion.py
smarthomeconnect/test/test_data_logging.py
smarthomeconnect/test/test_datatypes.py
smarthomeconnect/test/test_examples.py
smarthomeconnect/test/test_expressions.py
smarthomeconnect/test/test_interfaces_stub.py
smarthomeconnect/test/test_misc.py
smarthomeconnect/test/test_timer.py
smarthomeconnect/test/test_variables.py
smarthomeconnect/test/test_web.py
```

2025-01-16 08:18 UTC, jo47011 commented on setup.cfg
> -    Framework :: AsyncIO
Whoops, good catch.  Added them to `pyproject.toml`:
```bash
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Home Automation",
    "Framework :: AsyncIO"
]
```

2025-01-16 08:25 UTC, jo47011 commented on setup.cfg
> -    Tracker = https://github.com/mhthies/smarthomeconnect/issues
🙈 sorry, added again:
```bash
[project.urls]
Documentation = "https://smarthomeconnect.readthedocs.org/"
Source = "https://github.com/mhthies/smarthomeconnect"
Tracker = "https://github.com/mhthies/smarthomeconnect/issues"
```

2025-01-16 08:34 UTC, jo47011 commented on setup.cfg
> -license_files = NOTICE, LICENSE
fixed:
```bash
[project]
...
readme = { file = "README.md", content-type = "text/markdown" }

[tool.setuptools]
license-files = ["LICENSE", "NOTICE"]
```

```bash
unzip -p smarthomeconnect-0.9.0-py3-none-any.whl smarthomeconnect-0.9.0.dist-info/METADATA

Metadata-Version: 2.2
Name: smarthomeconnect
Version: 0.9.0
Summary: The Smart Home Connect home automation framework based on AsyncIO
Author-email: Michael Thies <mail@mhthies.de>
License: 
                                         Apache License
                                   Version 2.0, January 2004
                                http://www.apache.org/licenses/
        
           TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
```

2025-01-16 08:35 UTC, jo47011 commented on pyproject.toml
> +preview = true
removed.

2025-01-16 08:42 UTC, jo47011 commented on scripts/extract_dependencies.py
> +        return []
Ok, no problem => removed.

2025-01-18 16:31 UTC, mhthies commented on setup.cfg
> -    Framework :: AsyncIO
Thanks! :)

I think we can keep  `Programming Language :: Python :: 3.8` and the versions in between, as well to show Python version compatibility on PyPI.

2025-01-18 16:51 UTC, mhthies approved these changes

2025-01-18 16:51 UTC, merged